

trigger:
    branches:
      include:
        - master
        
variables:
    packageName: 'socketx-client-swift'
    packageDirectory: '$(Build.Repository.LocalPath)'


pool: 'MacOS - Intel'

steps:

- task: InstallSSHKey@0
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Install the SSH key'
  inputs:
    knownHostsEntry: '$(known_hosts_entry)'
    sshPublicKey: '$(ado_pk)'
    sshKeySecureFile: 'id_ed25519'

- task: DeleteFiles@1
  displayName: 'Delete unnecessary files before push to public remote'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/master')
             )
  inputs:
    SourceFolder: $(packageDirectory)
    Contents: |
      .gitignore
      **/*.yml
      dev_docs
      release.sh

- script: |
    git add .
    git commit -am 'Commit unnecessary file deletion'
  displayName: 'Commit unnecessary file deletion'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/master')
             )
  workingDirectory: $(packageDirectory)

- task: CmdLine@2
  displayName: 'Push to Public GitHub'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/master')
             )
  inputs:
    script: |
      ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
      git push git@github.com:Eclypses/$(Build.Repository.Name).git HEAD:refs/heads/public --force  --tags
    workingDirectory: $(packageDirectory)

